### PR TITLE
Add createWriteStreamWatch

### PR DESCRIPTION
**Pull request by N44PS**
Hello,

I've been using your module to read and write torrent files, I needed to check the writable stream was close but couldn't with the createWriteStream function itself.

Thank you ! :)

### CODE REVIEW

**Comment by fent** [comment]
Ah nice. Would you say it's more common for people to use the writable stream instead of the readable? Maybe we should return both of them in an object? What do you think?

**Comment by N44PS** [comment]
Your question made me realise I should have checked about your documentation and tests.

To write a torrent file from a source you do as follow : 
```
nt.read() => torrent.createWriteStream() => nt.read(). 
```
```javascript
'Read': {
      topic: function() {
        nt.read(file1, this.callback);
      },

      'Info hash from read file matches': function(torrent) {
        assert.isObject(torrent.metadata);
        assert.equal(torrent.infoHash(),
          'a38d02c287893842a32825aa866e00828a318f07');
      },

      'then write new torrent file': {
        topic: function(torrent) {
          var rs = torrent.createWriteStream(output2);
          var callback = this.callback;

          nt.read(rs, function(err, torrent) {
            fs.unlink(output2);
            callback(err, torrent);
          });
        },
...
```


In my app, I do as follow :
```
nt.read() => torrent.createWriteStream().on('close');
```
```javascript
nt.read(file, function(torrent) {
  torrent.createWriteStreamWatch(output).on('close', function(){
      console.log("do what I want with the torrent file", output);
      fs.unlink(output);
    });
  });
});
```

Maybe I'm wrong and someone needs the readable stream, but I guess returning the writable stream removes a step.

Thank you :)

**Comment by fent** [comment]
So, would you like this merged in? Are you going to be making changes? Are you going to use the readable stream instead?

**Comment by N44PS** [comment]
To me it makes more sense that people currently using ```createWriteStream``` and his readable stream should use ```createReadStream```.

Those that want to use the ```createWriteStream``` and his writable stream should use the new ```createWriteStream``` (which is the ```createWriteStreamWatch```).

Also, I found out you were using ```createWriteStream``` my way here : 
https://github.com/fent/node-torrent/blob/master/bin/nt.js#L337-346 
I tried this before and it didn't work, still doesn't, that's why I wanted to get the writable stream returned instead.

**Comment by fent** [comment]
Yeah, that does make a bit more sense. Can you fix the tests and update the readme?

**Comment by fent** [comment]
Thanks!

**Pull request merged**
